name: CMake Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/dist

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Compress
      run: 7z a -tzip ${{github.workspace}}/dist/${{github.ref_name}}-${{matrix.os}}.zip ${{github.workspace}}/build/dist/*

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.ref_name}}-${{matrix.os}}.zip
        path: ${{github.workspace}}/dist/${{github.ref_name}}-${{matrix.os}}.zip

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download
      uses: actions/download-artifact@v2
      with:
        path: ${{github.workspace}}/dist

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: ${{github.workspace}}/dist/**/*.zip
